---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: clickhouse 
  - src: https://github.com/Ingvar78/vector-role.git
    scm: git
    version: 1.0.0
    name: vector-role
  - src: https://github.com/Ingvar78/lighthouse-role.git
    scm: git
    version: 1.0.0
    name: lighthouse-role
  - src: https://github.com/Ingvar78/nginx-role.git
    scm: git
    version: 1.0.5
    name: nginx-role